import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const SHOP_ITEMS = [
    // ── Avatar Frames ──────────────────────────────────────
    {
        name: "Lingkaran Api",
        description: "Bingkai berkilap berwarna oranye-merah yang membara.",
        price: 75,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #ff6b35, #f7c59f, #e63946, #ff6b35)",
        previewColor: "#ff6b35",
    },
    {
        name: "Cincin Emas",
        description: "Bingkai mewah bergradasi emas untuk explorer sejati.",
        price: 150,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #f9c74f, #f8961e, #f3722c, #f9c74f)",
        previewColor: "#f9c74f",
    },
    {
        name: "Neon Cyan",
        description: "Bingkai bercahaya warna cyan neon modern.",
        price: 100,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #00f5d4, #00bbf9, #4361ee, #00f5d4)",
        previewColor: "#00f5d4",
    },
    {
        name: "Pelangi Ajaib",
        description: "Bingkai dengan semua warna pelangi yang memukau.",
        price: 250,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3, #54a0ff, #ff6b6b)",
        previewColor: "#ff6b6b",
    },
    // ── Profile Banners ─────────────────────────────────────
    {
        name: "Aurora Boreal",
        description: "Latar hijau-cyan bergelombang seperti cahaya aurora utara.",
        price: 100,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #0f3460 0%, #16213e 30%, #0d7377 60%, #14a085 100%)",
        previewColor: "#0d7377",
    },
    {
        name: "Langit Senja",
        description: "Gradasi merah-oranye-ungu indah seperti matahari terbenam.",
        price: 125,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #2d1b69 0%, #8b1a1a 30%, #d4541a 60%, #e8852b 100%)",
        previewColor: "#d4541a",
    },
    {
        name: "Galaxy Dalam",
        description: "Latar hitam penuh bintang dan nebula berwarna.",
        price: 200,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #0a0a0f 0%, #1a0a2e 25%, #0d1a3a 50%, #1e0040 75%, #0a0a0f 100%)",
        previewColor: "#1a0a2e",
    },
    {
        name: "Sakura Malam",
        description: "Gradasi pink-merah muda hening seperti bunga sakura.",
        price: 150,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #1a0a1e 0%, #3d1040 30%, #8b3a6e 60%, #c97ba8 100%)",
        previewColor: "#8b3a6e",
    },
    {
        name: "Lautan Biru",
        description: "Gradasi biru dalam seperti samudra tak berujung.",
        price: 100,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #0a1628 0%, #0d3b6e 40%, #1565c0 70%, #1e88e5 100%)",
        previewColor: "#1565c0",
    },
    // ── Profile Banners Baru ────────────────────────────────
    {
        name: "Bayangan Krimson",
        description: "Hitam ke merah tua gelap dengan lingkaran samar.",
        price: 175,
        type: "PROFILE_BANNER" as const,
        value: "radial-gradient(circle at 18% 50%, transparent 15%, rgba(180,0,80,0.18) 16.5%, transparent 18.5%, rgba(160,0,70,0.12) 29%, transparent 30.5%, rgba(140,0,60,0.07) 42%, transparent 43.5%), linear-gradient(135deg, #0a0a0a 0%, #1a0010 40%, #3d0030 70%, #6b003a 100%)",
        previewColor: "#3d0030",
    },
    {
        name: "Hutan Digital",
        description: "Gradasi hijau dengan efek batang-batang kode matrix.",
        price: 220,
        type: "PROFILE_BANNER" as const,
        value: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='140'%3E%3Crect x='18' y='70' width='15' height='70' rx='2' fill='%2300cc55' opacity='0.5'/%3E%3Crect x='39' y='42' width='15' height='98' rx='2' fill='%2300cc55' opacity='0.6'/%3E%3Crect x='60' y='18' width='15' height='122' rx='2' fill='%2300bb44' opacity='0.7'/%3E%3Crect x='81' y='28' width='15' height='112' rx='2' fill='%2300cc55' opacity='0.65'/%3E%3Crect x='102' y='54' width='15' height='86' rx='2' fill='%2300bb44' opacity='0.55'/%3E%3Crect x='123' y='78' width='15' height='62' rx='2' fill='%2300aa33' opacity='0.45'/%3E%3C/svg%3E\") left center / 200px 100% no-repeat, linear-gradient(135deg, #001a0a 0%, #003320 35%, #005233 65%, #007a4d 100%)",
        previewColor: "#005233",
    },
    {
        name: "Pasir Gurun Senja",
        description: "Coklat tembaga hangat dengan ornamen melingkar.",
        price: 140,
        type: "PROFILE_BANNER" as const,
        value: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Ccircle cx='75' cy='75' r='58' fill='none' stroke='%23d4900a' stroke-width='1.5' opacity='0.32'/%3E%3Cellipse cx='75' cy='75' rx='35' ry='58' fill='none' stroke='%23d4900a' stroke-width='1.5' opacity='0.26'/%3E%3Cellipse cx='75' cy='75' rx='16' ry='58' fill='none' stroke='%23d4900a' stroke-width='1' opacity='0.18'/%3E%3Cline x1='17' y1='75' x2='133' y2='75' stroke='%23d4900a' stroke-width='1' opacity='0.22'/%3E%3Cline x1='22' y1='47' x2='128' y2='47' stroke='%23d4900a' stroke-width='1' opacity='0.16'/%3E%3Cline x1='22' y1='103' x2='128' y2='103' stroke='%23d4900a' stroke-width='1' opacity='0.16'/%3E%3C/svg%3E\") right center / 155px 155px no-repeat, linear-gradient(135deg, #1a0a00 0%, #3d1f00 30%, #7a3f00 60%, #b35900 100%)",
        previewColor: "#7a3f00",
    },
    {
        name: "Langit Biru Cerah",
        description: "Gradasi biru muda siang hari dengan awan lembut.",
        price: 110,
        type: "PROFILE_BANNER" as const,
        value: "radial-gradient(ellipse 130px 55px at 28% 60%, rgba(255,255,255,0.48) 0%, transparent 100%), radial-gradient(ellipse 100px 42px at 68% 42%, rgba(255,255,255,0.38) 0%, transparent 100%), linear-gradient(135deg, #e8f4f8 0%, #b8d8f0 30%, #88b8e8 65%, #5090c0 100%)",
        previewColor: "#88b8e8",
    },
    {
        name: "Samudra Bintang",
        description: "Malam penuh bintang dan aurora ungu-biru yang meluas — banner terlebar untuk tampilan spektakuler.",
        price: 300,
        type: "PROFILE_BANNER" as const,
        value: "radial-gradient(ellipse 180px 100px at 45% 65%, rgba(100,50,200,0.48) 0%, transparent 75%), url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='140'%3E%3Ccircle cx='30' cy='20' r='1' fill='white' opacity='0.8'/%3E%3Ccircle cx='90' cy='35' r='1.2' fill='white' opacity='0.7'/%3E%3Ccircle cx='150' cy='15' r='0.8' fill='white' opacity='0.9'/%3E%3Ccircle cx='200' cy='28' r='1' fill='white' opacity='0.6'/%3E%3Ccircle cx='260' cy='12' r='1.3' fill='white' opacity='0.75'/%3E%3Ccircle cx='320' cy='30' r='0.9' fill='white' opacity='0.8'/%3E%3Ccircle cx='370' cy='18' r='1.1' fill='white' opacity='0.65'/%3E%3Ccircle cx='50' cy='60' r='0.8' fill='white' opacity='0.5'/%3E%3Ccircle cx='110' cy='75' r='1' fill='white' opacity='0.65'/%3E%3Ccircle cx='170' cy='55' r='1.2' fill='white' opacity='0.7'/%3E%3Ccircle cx='230' cy='80' r='0.8' fill='white' opacity='0.55'/%3E%3Ccircle cx='290' cy='65' r='1.1' fill='white' opacity='0.6'/%3E%3Ccircle cx='355' cy='85' r='0.9' fill='white' opacity='0.7'/%3E%3Ccircle cx='20' cy='105' r='1' fill='white' opacity='0.6'/%3E%3Ccircle cx='80' cy='118' r='0.8' fill='white' opacity='0.5'/%3E%3Ccircle cx='142' cy='102' r='1.3' fill='white' opacity='0.65'/%3E%3Ccircle cx='382' cy='112' r='1' fill='white' opacity='0.55'/%3E%3C/svg%3E\") 0 0 / 100% 100% no-repeat, linear-gradient(90deg, #0a0520 0%, #1a1040 25%, #0d0a2a 50%, #200a40 75%, #0a0520 100%)",
        previewColor: "#1a1040",
    },
    // ── Memory Card Themes ──────────────────────────────────
    {
        name: "Polaroid",
        description: "Tampilan kartu kenangan seperti foto polaroid klasik dengan bingkai putih.",
        price: 175,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "4px solid #f5f0e8",
            background: "#f5f0e8",
            shadow: "0 8px 32px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.3)",
            imageFilter: "sepia(15%) contrast(1.05) brightness(1.02)",
            radius: "4px",
            contentPadding: "p-3 pb-6",
            titleColor: "#1a1a1a",
            storyColor: "#4a4a4a",
            footerBorder: "border-t border-neutral-200",
            footerTextColor: "text-neutral-500",
        }),
        previewColor: "#f5f0e8",
    },
    {
        name: "Vintage",
        description: "Efek sepia hangat seperti foto jadul dari era 70-an.",
        price: 150,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "2px solid #7c5c2e",
            background: "linear-gradient(160deg, #1a1208 0%, #2a1f0e 100%)",
            shadow: "0 8px 32px rgba(100,60,10,0.4), inset 0 1px 0 rgba(255,200,100,0.05)",
            imageFilter: "sepia(60%) contrast(0.9) brightness(0.95) saturate(0.8)",
            radius: "8px",
            contentPadding: "p-4",
            titleColor: "#d4aa70",
            storyColor: "#a08060",
            footerBorder: "border-t border-amber-900/40",
            footerTextColor: "text-amber-800/70",
        }),
        previewColor: "#7c5c2e",
    },
    {
        name: "Dark Minimal",
        description: "Tampilan kartu bersih dengan border tipis neon dan font modern.",
        price: 140,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid rgba(99,102,241,0.5)",
            background: "linear-gradient(160deg, rgba(10,10,20,0.98), rgba(5,5,15,0.99))",
            shadow: "0 0 24px rgba(99,102,241,0.12), 0 8px 32px rgba(0,0,0,0.6)",
            imageFilter: "contrast(1.1) brightness(0.95) saturate(1.1)",
            radius: "16px",
            contentPadding: "p-5",
            titleColor: "#e0e7ff",
            storyColor: "#6b7280",
            footerBorder: "border-t border-indigo-500/20",
            footerTextColor: "text-indigo-400/60",
        }),
        previewColor: "#6366f1",
    },
    // ── Memory Card Themes Baru ─────────────────────────────
    {
        name: "Musim Hujan",
        description: "Biru muda segar seperti langit saat hujan gerimis di sore hari.",
        price: 130,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid #b2d8e8",
            background: "radial-gradient(circle at 78% 25%, transparent 10%, rgba(21,101,192,0.12) 11.5%, transparent 13%, rgba(21,101,192,0.08) 21%, transparent 22.5%), radial-gradient(circle at 22% 72%, transparent 7%, rgba(21,101,192,0.09) 8.5%, transparent 10%, rgba(21,101,192,0.05) 17%, transparent 18.5%), repeating-linear-gradient(170deg, transparent 0px, transparent 18px, rgba(21,101,192,0.05) 18px, rgba(21,101,192,0.05) 19px), linear-gradient(160deg, #e8f4f8 0%, #d0eaf5 50%, #b8dff0 100%)",
            shadow: "0 8px 32px rgba(21,101,192,0.15), 0 2px 8px rgba(21,101,192,0.1)",
            imageFilter: "contrast(0.97) brightness(1.03) saturate(0.9) hue-rotate(5deg)",
            radius: "12px",
            contentPadding: "p-4",
            titleColor: "#01579b",
            storyColor: "#0277bd",
            footerBorder: "border-t border-blue-200",
            footerTextColor: "text-blue-400",
        }),
        previewColor: "#b8dff0",
    },
    {
        name: "Perkamen Emas",
        description: "Kertas kuno berwarna krem dengan aksen emas mewah di bagian atas.",
        price: 180,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid #c4a060",
            background: "linear-gradient(rgba(180,120,0,0.07) 1px, transparent 1px) 0 0 / 100% 28px, linear-gradient(90deg, rgba(180,120,0,0.04) 1px, transparent 1px) 0 0 / 36px 100%, linear-gradient(160deg, #fff8f0 0%, #fdf0e0 50%, #f8e8cc 100%)",
            shadow: "0 8px 32px rgba(180,120,0,0.2), inset 0 1px 0 rgba(255,220,100,0.3)",
            imageFilter: "sepia(20%) contrast(1.02) brightness(1.01) saturate(0.95)",
            radius: "6px",
            contentPadding: "p-4",
            titleColor: "#7a4a00",
            storyColor: "#a06020",
            footerBorder: "border-t border-amber-300/60",
            footerTextColor: "text-amber-700/70",
        }),
        previewColor: "#c4a060",
    },
    {
        name: "Neon Merah Malam",
        description: "Hitam pekat dengan aksen garis dan teks merah neon yang membakar.",
        price: 200,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid rgba(255,0,102,0.4)",
            background: "radial-gradient(circle 24px at calc(100% - 20px) calc(100% - 20px), rgba(255,0,102,0.75) 0%, rgba(255,0,102,0.3) 50%, transparent 75%), linear-gradient(160deg, #0a0008 0%, #150010 50%, #1a0015 100%)",
            shadow: "0 0 20px rgba(255,0,102,0.1), 0 8px 32px rgba(0,0,0,0.7)",
            imageFilter: "contrast(1.15) brightness(0.9) saturate(1.2)",
            radius: "14px",
            contentPadding: "p-5",
            titleColor: "#ff80aa",
            storyColor: "#884466",
            footerBorder: "border-t border-rose-900/40",
            footerTextColor: "text-rose-500/60",
        }),
        previewColor: "#ff0066",
    },
    {
        name: "Daun Teh",
        description: "Hijau segar alami seperti kebun teh di pagi hari yang sejuk.",
        price: 125,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid #80c0a0",
            background: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='90' height='90'%3E%3Cpath d='M80,8 C80,8 18,14 8,76 C30,58 58,34 80,8Z' fill='rgba(45,138,86,0.14)'/%3E%3Cpath d='M80,8 C58,30 34,56 8,76' fill='none' stroke='rgba(45,138,86,0.22)' stroke-width='1.5'/%3E%3Cpath d='M44,42 L8,76' fill='none' stroke='rgba(45,138,86,0.13)' stroke-width='1'/%3E%3Cpath d='M62,24 L44,42' fill='none' stroke='rgba(45,138,86,0.13)' stroke-width='1'/%3E%3C/svg%3E\") top right / 90px 90px no-repeat, linear-gradient(160deg, #e8f8f0 0%, #d0f0e0 50%, #b8e8d0 100%)",
            shadow: "0 8px 32px rgba(45,138,86,0.15), 0 2px 8px rgba(45,138,86,0.08)",
            imageFilter: "contrast(0.98) brightness(1.02) saturate(1.05) hue-rotate(-5deg)",
            radius: "10px",
            contentPadding: "p-4",
            titleColor: "#1a5c38",
            storyColor: "#2d7a50",
            footerBorder: "border-t border-green-300/60",
            footerTextColor: "text-green-600/70",
        }),
        previewColor: "#80c0a0",
    },
    {
        name: "Mistik Ungu",
        description: "Ungu gelap misterius dengan lingkaran konsentrik samar di latar.",
        price: 240,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid rgba(127,119,221,0.5)",
            background: "radial-gradient(circle at 85% 82%, transparent 14%, rgba(127,119,221,0.22) 15.5%, transparent 17%, rgba(100,90,200,0.14) 27%, transparent 28.5%, rgba(90,80,180,0.08) 40%, transparent 41.5%), linear-gradient(160deg, #1a1028 0%, #2a1840 50%, #1a1028 100%)",
            shadow: "0 0 28px rgba(127,119,221,0.12), 0 8px 32px rgba(0,0,0,0.65)",
            imageFilter: "contrast(1.08) brightness(0.93) saturate(1.1) hue-rotate(260deg)",
            radius: "16px",
            contentPadding: "p-5",
            titleColor: "#d0a0ff",
            storyColor: "#9060c0",
            footerBorder: "border-t border-purple-800/40",
            footerTextColor: "text-purple-400/60",
        }),
        previewColor: "#7f77dd",
    },
    // ── Memory Stickers ─────────────────────────────────────
    {
        name: "Catatan Kuning",
        description: "Post-it kuning klasik yang bisa ditempel miring di foto kenangan.",
        price: 80,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "sticky-note",
            background: "#fff9c4",
            border: "1px solid #f9c74f",
            textColor: "#7a4a00",
            defaultRotation: -3,
            defaultText: "Tempat Favorit",
            subText: "Selalu ingin kembali",
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 110,
            height: 75,
        }),
        previewColor: "#fff9c4",
    },
    {
        name: "Catatan Merah Muda",
        description: "Post-it pink lembut untuk kenangan penuh kasih sayang.",
        price: 80,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "sticky-note",
            background: "#ffe0f0",
            border: "1px solid #f4c0d1",
            textColor: "#72243e",
            defaultRotation: 2,
            defaultText: "Kenangan Indah",
            subText: null,
            icon: "heart",
            iconColor: "#d4537e",
            iconPosition: "top-right",
            editable: true,
            width: 110,
            height: 75,
        }),
        previewColor: "#ffe0f0",
    },
    {
        name: "Label Pita Merah",
        description: "Ribbon label merah-oranye menyala untuk highlight momen terbaik.",
        price: 90,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "ribbon",
            background: "linear-gradient(135deg, #ff6b6b, #ee5a24)",
            border: "none",
            textColor: "#ffffff",
            defaultRotation: 1,
            defaultText: "Kenangan Terbaik",
            subText: null,
            accentBackground: "linear-gradient(135deg, #f9c74f, #f8961e)",
            accentTextColor: "#5a2d00",
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: false,
            width: 140,
            height: 36,
        }),
        previewColor: "#ee5a24",
    },
    {
        name: "Label Pita Ungu",
        description: "Ribbon label ungu elegan untuk menandai momen spesial.",
        price: 90,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "ribbon",
            background: "linear-gradient(135deg, #7f77dd, #534ab7)",
            border: "none",
            textColor: "#eeedfe",
            defaultRotation: -1,
            defaultText: "Momen Spesial",
            subText: null,
            accentBackground: "linear-gradient(135deg, #afa9ec, #7f77dd)",
            accentTextColor: "#26215c",
            icon: "star",
            iconColor: "#eeedfe",
            iconPosition: "inline",
            editable: false,
            width: 140,
            height: 36,
        }),
        previewColor: "#7f77dd",
    },
    {
        name: "Cap Tanggal",
        description: "Stempel bulat yang bisa dikustomisasi tanggalnya.",
        price: 60,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "stamp",
            background: "#ffffff",
            border: "1.5px solid #e0e0e0",
            textColor: "#e24b4a",
            defaultRotation: 0,
            defaultText: "",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 68,
            height: 68,
        }),
        previewColor: "#ffffff",
    },
    {
        name: "Tag Lokasi",
        description: "Tag berbentuk label nama tempat yang bisa dikustomisasi.",
        price: 75,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "tag",
            background: "#e6f1fb",
            border: "1px solid #85b7eb",
            textColor: "#0c447c",
            defaultRotation: 0,
            defaultText: "Nama Tempat",
            subText: null,
            icon: "map-pin",
            iconColor: "#185fa5",
            iconPosition: "inline",
            editable: true,
            width: 120,
            height: 34,
        }),
        previewColor: "#85b7eb",
    },
    {
        name: "Bintang Pilihan",
        description: "Stiker bintang emas besar untuk menandai momen paling berkesan.",
        price: 55,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "star",
            background: "#f9c74f",
            border: "none",
            textColor: "#7a4a00",
            defaultRotation: 5,
            defaultText: "Top Momen",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: false,
            width: 70,
            height: 70,
        }),
        previewColor: "#f9c74f",
    },
    {
        name: "Segel Petualang",
        description: "Badge heksagonal ungu gelap bergaya segel ekspedisi petualangan.",
        price: 120,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "badge",
            background: "linear-gradient(135deg, #1a1030, #2a1840)",
            border: "1.5px solid #7f77dd",
            textColor: "#afa9ec",
            defaultRotation: 0,
            defaultText: "Petualangan Seru",
            subText: null,
            icon: "star",
            iconColor: "#7f77dd",
            iconPosition: "inline",
            editable: false,
            width: 150,
            height: 38,
        }),
        previewColor: "#534ab7",
    },
    {
        name: "Label Kosong",
        description: "Stiker kosong yang bisa kamu isi dengan teks sendiri (maks 20 karakter).",
        price: 50,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "tag",
            background: "#f0f0f5",
            border: "1px solid #c0c0d0",
            textColor: "#2d2d3a",
            defaultRotation: 0,
            defaultText: "Kustom",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 120,
            height: 34,
        }),
        previewColor: "#c0c0d0",
    },
    // ── Username Decorations ────────────────────────────────
    {
        name: "Neon Ungu",
        description: "Nama bersinar neon ungu-biru yang futuristik.",
        price: 250,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #d946ef, #a855f7, #6366f1)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 12px rgba(217,70,239,0.7))"
        }),
        previewColor: "#d946ef",
    },
    {
        name: "Emas Berkilau",
        description: "Nama bersinar gradasi emas mewah dengan efek kilau.",
        price: 400,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #fef08a, #facc15, #eab308, #ca8a04)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 15px rgba(250,204,21,0.6))"
        }),
        previewColor: "#facc15",
    },
    {
        name: "Api Membara",
        description: "Nama membara dengan gradasi api oranye-merah.",
        price: 180,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #ff6b35, #f7c59f, #e63946, #ff6b35)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 10px rgba(231,57,70,0.6))"
        }),
        previewColor: "#ff6b35",
    },
    {
        name: "Pelangi Kosmik",
        description: "Nama berwarna pelangi penuh warna seperti nebula bintang.",
        price: 325,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3, #54a0ff, #ff6b6b)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 8px rgba(72,219,251,0.5))"
        }),
        previewColor: "#48dbfb",
    },
    {
        name: "Kristal Biru",
        description: "Nama bersih dengan efek biru es yang elegan.",
        price: 140,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #00f5d4, #00bbf9, #4361ee)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 10px rgba(0,187,249,0.55))"
        }),
        previewColor: "#00bbf9",
    },
    // ── Epic & Legend Avatar Frames ─────────────────────────
    {
        name: "Orbit Void",
        description: "Cincin energi ungu-magenta yang mengorbit dalam kekosongan gelap tanpa dasar.",
        price: 220,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #0a0015 0%, #2d1b69 15%, #8b5cf6 30%, #c026d3 50%, #8b5cf6 70%, #2d1b69 85%, #0a0015 100%)",
        previewColor: "#8b5cf6",
    },
    {
        name: "Fraktur Waktu",
        description: "Bingkai retak-retak dengan distorsi digital — seolah ruang-waktu pecah di sekitar avatar.",
        price: 250,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #00ffff 0%, #ff0040 20%, #00ffff 40%, #ff0040 60%, #00ffff 80%, #ff0040 100%)",
        previewColor: "#00ffff",
    },
    {
        name: "Singularitas",
        description: "Tepi event horizon — cahaya biru-putih yang runtuh ke dalam kegelapan absolut.",
        price: 300,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #000000 0%, #0a0a2e 10%, #1e3a8a 22%, #3b82f6 35%, #93c5fd 45%, #ffffff 50%, #93c5fd 55%, #3b82f6 65%, #1e3a8a 78%, #0a0a2e 90%, #000000 100%)",
        previewColor: "#3b82f6",
    },
    {
        name: "Cakra Nebula",
        description: "Lingkaran nebula hidup — magenta, ungu, dan cyan berputar mengelilingi avatar tanpa henti.",
        price: 350,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #7c3aed 0%, #db2777 18%, #06b6d4 36%, #a855f7 54%, #ec4899 72%, #0891b2 90%, #7c3aed 100%)",
        previewColor: "#db2777",
    },
    {
        name: "Mata Eternum",
        description: "Avatar menjadi pupil dari mata kosmik — aura emas-putih menyala ke segala arah.",
        price: 400,
        type: "AVATAR_FRAME" as const,
        value: "linear-gradient(135deg, #fef08a 0%, #fbbf24 15%, #ffffff 30%, #fde68a 50%, #f59e0b 70%, #ffffff 85%, #fef08a 100%)",
        previewColor: "#fbbf24",
    },
    // ── Epic & Legend Username Decorations ──────────────────
    {
        name: "Glitch Dimensi",
        description: "Teks berkedip dalam distorsi merah-cyan — sinyal dari dimensi lain yang tak stabil.",
        price: 200,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #ff0040, #00ffff, #ff0040, #00ffff, #ff0040)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 14px rgba(255,0,64,0.65)) drop-shadow(2px -2px 0 rgba(0,255,255,0.45))"
        }),
        previewColor: "#ff0040",
    },
    {
        name: "Denyut Quasar",
        description: "Gradasi hijau-cyan berdenyut seperti pulsar energi kosmik yang baru lahir.",
        price: 240,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #00ff87, #60efff, #00d2ff, #00ff87, #60efff)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 16px rgba(0,255,135,0.7)) drop-shadow(0 0 36px rgba(96,239,255,0.35))"
        }),
        previewColor: "#00ff87",
    },
    {
        name: "Aksara Celestial",
        description: "Huruf berpijar emas-putih surgawi — seolah ditulis oleh bintang itu sendiri.",
        price: 450,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #fffacd, #ffd700, #ffffff, #ffd700, #fffacd, #ffd700)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 20px rgba(255,215,0,0.85)) drop-shadow(0 0 44px rgba(255,215,0,0.45)) drop-shadow(0 0 8px rgba(255,255,255,0.6))"
        }),
        previewColor: "#ffd700",
    },
    {
        name: "Jejak Supernova",
        description: "Ledakan warna merah, oranye, magenta, dan biru — sisa jejak supernova yang membara.",
        price: 380,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #ff4444, #ff8800, #ff00aa, #4488ff, #ff00aa, #ff4444)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 16px rgba(255,0,170,0.7)) drop-shadow(0 0 34px rgba(255,136,0,0.45)) drop-shadow(0 0 8px rgba(255,68,68,0.5))"
        }),
        previewColor: "#ff00aa",
    },
    {
        name: "Rune Primordial",
        description: "Teks ungu tua mistis dengan glow berdenyut — aksara kuno dari zaman purba yang terlupakan.",
        price: 400,
        type: "USERNAME_DECORATION" as const,
        value: JSON.stringify({
            background: "linear-gradient(90deg, #7c3aed, #a855f7, #e9d5ff, #a855f7, #7c3aed, #a855f7)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            filter: "drop-shadow(0 0 18px rgba(124,58,237,0.8)) drop-shadow(0 0 40px rgba(168,85,247,0.45)) drop-shadow(0 0 8px rgba(233,213,255,0.5))"
        }),
        previewColor: "#7c3aed",
    },
    // ── Legend Memory Card Themes ───────────────────────────
    {
        name: "Void Kristal",
        description: "Kartu hitam absolut dengan border kristal biru es yang memantulkan cahaya dingin.",
        price: 350,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1.5px solid rgba(147,197,253,0.6)",
            background: "radial-gradient(ellipse 200px 120px at 80% 20%, rgba(59,130,246,0.12) 0%, transparent 70%), radial-gradient(ellipse 150px 100px at 20% 80%, rgba(147,197,253,0.08) 0%, transparent 70%), radial-gradient(circle 60px at 50% 50%, rgba(96,165,250,0.06) 0%, transparent 100%), linear-gradient(160deg, #030308 0%, #050510 30%, #08081a 60%, #030308 100%)",
            shadow: "0 0 30px rgba(59,130,246,0.2), 0 0 60px rgba(147,197,253,0.08), 0 8px 32px rgba(0,0,0,0.8), inset 0 1px 0 rgba(147,197,253,0.1)",
            imageFilter: "contrast(1.15) brightness(0.88) saturate(1.2) hue-rotate(200deg)",
            radius: "16px",
            contentPadding: "p-5",
            titleColor: "#93c5fd",
            storyColor: "#3b82f6",
            footerBorder: "border-t border-blue-500/20",
            footerTextColor: "text-blue-400/50",
        }),
        previewColor: "#3b82f6",
    },
    {
        name: "Eter Galaktik",
        description: "Kartu bernuansa nebula gelap — bintang-bintang kecil dan aura ungu-magenta dari kedalaman galaksi.",
        price: 300,
        type: "MEMORY_CARD_THEME" as const,
        value: JSON.stringify({
            border: "1px solid rgba(168,85,247,0.4)",
            background: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='200'%3E%3Ccircle cx='25' cy='18' r='1' fill='white' opacity='0.85'/%3E%3Ccircle cx='78' cy='42' r='1.3' fill='white' opacity='0.7'/%3E%3Ccircle cx='140' cy='12' r='0.8' fill='white' opacity='0.9'/%3E%3Ccircle cx='195' cy='35' r='1.1' fill='white' opacity='0.6'/%3E%3Ccircle cx='250' cy='22' r='1.4' fill='white' opacity='0.75'/%3E%3Ccircle cx='45' cy='78' r='0.9' fill='white' opacity='0.55'/%3E%3Ccircle cx='110' cy='95' r='1.2' fill='white' opacity='0.65'/%3E%3Ccircle cx='170' cy='68' r='0.7' fill='white' opacity='0.8'/%3E%3Ccircle cx='230' cy='88' r='1' fill='white' opacity='0.5'/%3E%3Ccircle cx='280' cy='55' r='1.1' fill='white' opacity='0.7'/%3E%3Ccircle cx='15' cy='140' r='1' fill='white' opacity='0.6'/%3E%3Ccircle cx='65' cy='160' r='0.8' fill='white' opacity='0.5'/%3E%3Ccircle cx='130' cy='145' r='1.3' fill='white' opacity='0.65'/%3E%3Ccircle cx='200' cy='170' r='0.9' fill='white' opacity='0.55'/%3E%3Ccircle cx='260' cy='130' r='1.2' fill='white' opacity='0.7'/%3E%3Ccircle cx='290' cy='180' r='0.7' fill='white' opacity='0.6'/%3E%3C/svg%3E\") 0 0 / 100% 100% no-repeat, radial-gradient(ellipse 180px 130px at 70% 30%, rgba(219,39,119,0.18) 0%, transparent 70%), radial-gradient(ellipse 160px 110px at 25% 70%, rgba(124,58,237,0.15) 0%, transparent 70%), radial-gradient(ellipse 100px 80px at 50% 50%, rgba(6,182,212,0.08) 0%, transparent 80%), linear-gradient(160deg, #0a0518 0%, #120828 30%, #0d0620 60%, #0a0518 100%)",
            shadow: "0 0 28px rgba(168,85,247,0.15), 0 0 56px rgba(219,39,119,0.06), 0 8px 32px rgba(0,0,0,0.75), inset 0 1px 0 rgba(168,85,247,0.08)",
            imageFilter: "contrast(1.1) brightness(0.9) saturate(1.15) hue-rotate(270deg)",
            radius: "16px",
            contentPadding: "p-5",
            titleColor: "#d8b4fe",
            storyColor: "#a855f7",
            footerBorder: "border-t border-purple-500/20",
            footerTextColor: "text-purple-400/50",
        }),
        previewColor: "#a855f7",
    },
    // ── Special Memory Stickers (Exclusive — NOT in gacha pool) ──
    {
        name: "Cuddlysun",
        description: "Perangko vintage dengan hangatnya sinar mentari — kirim kenangan manismu.",
        price: 200,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "postcard",
            background: "#d8ecf8",
            border: "none",
            textColor: "#c8a84e",
            defaultRotation: -2,
            defaultText: "good memories",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 140,
            height: 105,
        }),
        previewColor: "#d8ecf8",
    },
    {
        name: "Shape Coquette",
        description: "Buku kenangan dengan hiasan pita emas elegan — simpan ceritamu dengan cantik.",
        price: 200,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "book",
            background: "#f5c6d0",
            border: "none",
            textColor: "#9a7030",
            defaultRotation: 0,
            defaultText: "good memories",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 150,
            height: 100,
        }),
        previewColor: "#f5c6d0",
    },
    {
        name: "Grape Blossom",
        description: "Jurnal lavender dengan sentuhan pita manis — abadikan momen yang tak pudar.",
        price: 200,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "notebook",
            background: "#fdf5e6",
            border: "none",
            textColor: "#b0a090",
            defaultRotation: 1,
            defaultText: "everlasting memory",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 150,
            height: 100,
        }),
        previewColor: "#d8b4fe",
    },
    {
        name: "Soft Bubble Tea",
        description: "Player musik pink aesthetic — setiap memori manis punya lagu tema tersendiri.",
        price: 200,
        type: "MEMORY_STICKER" as const,
        value: JSON.stringify({
            shape: "player",
            background: "#f8d0e0",
            border: "none",
            textColor: "#3a3a3a",
            defaultRotation: 0,
            defaultText: "good vibes only",
            subText: null,
            icon: null,
            iconColor: null,
            iconPosition: null,
            editable: true,
            width: 120,
            height: 130,
        }),
        previewColor: "#f8d0e0",
    },
    // ── Premium-Exclusive Items (auto-granted, NOT in shop/gacha) ────
    {
        name: "Mahkota Royale",
        description: "Bingkai premium neubrutalism dengan aksen emas tebal — eksklusif Premium member.",
        price: 0,
        type: "AVATAR_FRAME" as const,
        value: "repeating-conic-gradient(from 0deg, #ffd700 0deg 30deg, #000 30deg 60deg, #b8860b 60deg 90deg, #000 90deg 120deg)",
        previewColor: "#ffd700",
    },
    {
        name: "Langit Kerajaan",
        description: "Banner premium bergaya neubrutalism dengan aksen emas kerajaan — eksklusif Premium member.",
        price: 0,
        type: "PROFILE_BANNER" as const,
        value: "linear-gradient(135deg, #1a1508 0%, #2a2010 30%, #1a1508 50%, #2a2010 70%, #1a1508 100%)",
        previewColor: "#ffd700",
    },
]

async function main() {
    console.log("🌟 Seeding shop items...")

    const existing = await prisma.shopItem.findMany({ select: { name: true } })
    const existingNames = new Set(existing.map((i: { name: string }) => i.name))

    const toCreate = SHOP_ITEMS.filter((item) => !existingNames.has(item.name))

    if (toCreate.length > 0) {
        await prisma.shopItem.createMany({ data: toCreate })
        console.log(`✅ Created ${toCreate.length} shop items`)
    } else {
        console.log("⏭️  All shop items already exist, skipping.")
    }
}

main()
    .then(() => prisma.$disconnect())
    .catch((e) => {
        console.error(e)
        prisma.$disconnect()
        process.exit(1)
    })